param([Parameter(Mandatory=$true)][string]$RequestPath, [Parameter(Mandatory=$true)][string]$ResultPath, [string]$StatusPath)
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

function Upgrade-TelemetryKeys([string[]]$Lines, [string]$Sid) {
    if ($Sid -notmatch '^S-1-[0-9-]+$') { throw 'Invalid Windows account SID.' }
    $count = 0
    $updated = foreach ($line in $Lines) {
        # Only the exact restricted format generated by Dyno is eligible. Custom
        # entries, including entries with this marker but extra permissions, fail.
        if ($line -match (' dyno-worker-' + [regex]::Escape($Sid) + '-[^ ]+$')) {
            $pattern = '^from="(?<ip>[0-9.]+)",restrict,port-forwarding,permitopen="127\.0\.0\.1:50052",(?:permitopen="127\.0\.0\.1:50055",)?command="echo Dyno forwarding only" ssh-ed25519 [A-Za-z0-9+/]{68} dyno-worker-' + [regex]::Escape($Sid) + '-\k<ip>$'
            if ($line -notmatch $pattern) { throw 'A Dyno key has custom restrictions. No keys were changed.' }
            $ip = [Net.IPAddress]::Parse($Matches.ip)
            $b = $ip.GetAddressBytes()
            if ($b.Length -ne 4 -or -not ($b[0] -eq 10 -or ($b[0] -eq 172 -and $b[1] -ge 16 -and $b[1] -le 31) -or ($b[0] -eq 192 -and $b[1] -eq 168))) { throw 'Invalid paired LAN address. No keys were changed.' }
            $count++
            if ($line.Contains('permitopen="127.0.0.1:50055"')) { $line }
            else { $line.Replace('permitopen="127.0.0.1:50052",', 'permitopen="127.0.0.1:50052",permitopen="127.0.0.1:50055",') }
        } else { $line }
    }
    if (-not $count) { throw 'No existing Dyno pairing for this Windows account. Pair a coordinator first.' }
    return ,@($updated)
}

function Protect-AuthorizedKeys([string]$Path) {
    $acl = New-Object Security.AccessControl.FileSecurity
    $acl.SetAccessRuleProtection($true, $false)
    foreach ($sid in @('S-1-5-32-544', 'S-1-5-18')) {
        $identity = New-Object Security.Principal.SecurityIdentifier($sid)
        $rule = New-Object Security.AccessControl.FileSystemAccessRule($identity, 'FullControl', 'Allow')
        $acl.AddAccessRule($rule)
    }
    Set-Acl -LiteralPath $Path -AclObject $acl
}

try {
    $request = Get-Content -LiteralPath $RequestPath -Raw | ConvertFrom-Json
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    if ($identity.User.Value -ne $request.user_sid -or -not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { throw 'Approve with the same Windows administrator account that opened Dyno.' }
    if ($StatusPath) { 'Enabling telemetry for existing paired coordinators...' | Set-Content -LiteralPath $StatusPath -Encoding utf8 }
    $path = "$env:ProgramData\ssh\administrators_authorized_keys"
    $config = Get-Content -LiteralPath "$env:ProgramData\ssh\sshd_config" -Raw
    if ($config -notmatch '(?im)^\s*AuthorizedKeysFile\s+__PROGRAMDATA__/ssh/administrators_authorized_keys') { throw 'Custom SSH key configuration. No changes made.' }
    # Hold the file exclusively across read/validate/write; do not overwrite a
    # concurrent pairing update. No service restart, firewall or SSH config edit.
    Protect-AuthorizedKeys $path
    $stream = [IO.File]::Open($path, 'Open', 'ReadWrite', 'None')
    try {
        $reader = New-Object IO.StreamReader($stream, [Text.Encoding]::UTF8, $true, 1024, $true)
        $original = $reader.ReadToEnd()
        $reader.Dispose()
        $lines = @($original -split '\r?\n')
        $updated = Upgrade-TelemetryKeys $lines $request.user_sid
        $bytes = [Text.Encoding]::UTF8.GetBytes(($updated -join "`r`n"))
        $stream.Position = 0
        $stream.Write($bytes, 0, $bytes.Length)
        $stream.SetLength($bytes.Length)
        $stream.Flush($true)
    } finally { $stream.Dispose() }
    'Telemetry enabled. Existing pairing preserved. Reconnect the pool tunnel on your coordinator.' | Set-Content -LiteralPath $ResultPath -Encoding utf8
    exit 0
} catch {
    ('Telemetry setup failed: ' + $_.Exception.Message) | Set-Content -LiteralPath $ResultPath -Encoding utf8
    exit 1
}
